
services:
  db:
    image: bitnami/mariadb:latest
    ports:
      - "3306:3306"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/bitnami/mariadb 

  wordpress:
    image: bitnami/wordpress:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    
    volumes:
      - wp_data:/bitnami/wordpress

volumes:
  db_data:
  wp_data: